---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pac-interceptor
spec:
  replicas: 1
  selector:
    matchLabels:
      name: pac-interceptor
  template:
    metadata:
      labels:
        name: pac-interceptor
    spec:
      containers:
        - name: resolver
          image: "ko://github.com/savitaashture/pac-interceptor"
          ports:
            - name: pac-interceptor
              containerPort: 8800
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
---
apiVersion: v1
kind: Service
metadata:
  name: pac-interceptor
spec:
  ports:
    - name: http-listener
      protocol: TCP
      port: 8800
      targetPort: 8800
  selector:
    name: pac-interceptor
