---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app.kubernetes.io/part-of: pac-interceptor
    app.kubernetes.io/version: "devel"
  name: pac-interceptor
spec:
  port:
    targetPort: http-listener
  to:
    kind: Service
    name: pac-interceptor
    weight: 100
  wildcardPolicy: None
